id card and Licensees ox_inventory compatibility
Qbox-project/qbx-multicharacter pull request #18
Opened 2023-04-24 14:32 UTC by ARSSANTO

## Description

Yes https://github.com/Qbox-project/qbx-smallresources/pull/19
## Checklist

- [yes] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [] My code fits the style guidelines. not sure I feel like it's not the best code style can be more compressed
- [yes] My PR fits the contribution guidelines.

2023-04-26 08:01 UTC, Manason approved these changes

2023-04-27 21:30 UTC, FjamZoo requested changes

2023-04-27 21:30 UTC, FjamZoo commented on server/main.lua
> +                description = string.format('CID: %s  \nDOB: %s  \nGender: %s  \nNationality: %s ', citizenid, birthdate, gender, nationality),
instead of using description metadata for this utilize, https://overextended.github.io/docs/ox_inventory/Functions/Client/displayMetadata

Will essentially do the same without us having to store a big chunk of extra text in the Database

2023-04-27 21:30 UTC, FjamZoo commented on server/main.lua
> +                description = string.format('CID: %s  \nFirst Name: %s  \nLast Name: %s  \nDOB: %s  \nGender: %s  \nNationality: %s ', citizenid, firstname, lastname, birthdate, gender, nationality),
Utilize displayMetaData here aswell

2023-04-27 21:30 UTC, FjamZoo commented on server/main.lua
> +                description = string.format('CID: %s  \nFirst Name: %s  \nLast Name: %s  \nDOB: %s  \nGender: %s  \nNationality: %s ', citizenid, firstname, lastname, birthdate, gender, nationality),
Utilize displayMetaData here aswell

2023-04-28 06:34 UTC, ARSSANTO commented on server/main.lua
> +                description = string.format('CID: %s  \nFirst Name: %s  \nLast Name: %s  \nDOB: %s  \nGender: %s  \nNationality: %s ', citizenid, firstname, lastname, birthdate, gender, nationality),
yes i agree to reduce  big chunk of extra text in the db but I am confused RN how I can implement some condition from server side such as

`QBCore.Functions.CreateUseableItem("id_card", function(source, item)
	local playerPed = GetPlayerPed(source)
	local playerCoords = GetEntityCoords(playerPed)
	local players = QBCore.Functions.GetPlayers()
	for _, v in pairs(players) do
		local targetPed = GetPlayerPed(v)
		local dist = #(playerCoords - GetEntityCoords(targetPed))
		if dist < 3.0 then
			TriggerClientEvent('chat:addMessage', v,  {
					template = '<div class="chat-message advert"><div class="chat-message-body"><strong>{0}:</strong><br><br> <strong>Civ ID:</strong> {1} <br><strong>First Name:</strong> {2} <br><strong>Last Name:</strong> {3} <br><strong>Birthdate:</strong> {4} <br><strong>Gender:</strong> {5} <br><strong>Nationality:</strong> {6}</div></div>',
					args = {
						"ID Card",
						item.metadata.citizenid,
						item.metadata.firstname,
						item.metadata.lastname,
						item.metadata.birthdate,
						item.metadata.gender,
						item.metadata.nationality
					}
				}
			)
		end
	end
end)`

2023-04-28 10:35 UTC, FjamZoo commented on server/main.lua
> +                description = string.format('CID: %s  \nFirst Name: %s  \nLast Name: %s  \nDOB: %s  \nGender: %s  \nNationality: %s ', citizenid, firstname, lastname, birthdate, gender, nationality),
This is a very seperate PR, I care about this one for now I will help you make extra conditions for this on smallresources or whereever this was put as I do not really like that implementation

2023-04-29 08:44 UTC, Manason commented on server/main.lua
> +                description = string.format('CID: %s  \nDOB: %s  \nGender: %s  \nNationality: %s ', citizenid, birthdate, gender, nationality),
The issue with displayMetadata is no control over the ordering of the displayed keys. So storing a string that represents exactly what should be displayed is preferred.

2023-04-29 10:28 UTC, FjamZoo commented on server/main.lua
> +                description = string.format('CID: %s  \nDOB: %s  \nGender: %s  \nNationality: %s ', citizenid, birthdate, gender, nationality),
I still think its very much preferable to not store a 40-60 key long string in the database per ID card in the server, much rather have inconsistent displayed metadata IMO

Could also just do a Ox Inventory PR to fix that

2023-07-23 12:15 UTC, closed without merging